"""
CelesteOS - Prefill Engine Usage Examples
==========================================

Demonstrates how to use the prefill engine for different mutation types.

These examples show the field_metadata configurations for common mutations:
1. Create Work Order (with equipment lookup and composed title)
2. Create Fault Report (with equipment and symptom lookups)
3. Reorder Part (with part lookup and stock calculation)
4. Update Equipment Status (with status value mapping)
5. Assign Work Order (with user lookup)

Copy these patterns when implementing new /prepare endpoints.
"""

from common.field_metadata import FieldMetadata


# =============================================================================
# EXAMPLE 1: CREATE WORK ORDER
# =============================================================================
# Query: "create urgent work order for main engine overheating"
# Entities: {equipment: "main engine", symptom: "overheating", priority: "urgent"}

WORK_ORDER_FIELD_METADATA = {
    # CONTEXT fields - auto-populated from auth context
    "yacht_id": FieldMetadata(
        name="yacht_id",
        classification="CONTEXT",
        description="Yacht UUID from auth context",
    ),

    # BACKEND_AUTO fields - auto-generated by system
    "id": FieldMetadata(
        name="id",
        classification="BACKEND_AUTO",
        description="Work order UUID (auto-generated)",
    ),

    "wo_number": FieldMetadata(
        name="wo_number",
        classification="BACKEND_AUTO",
        description="Sequential work order number (auto-generated)",
        # Note: Actual generation happens in execute phase via DB trigger
    ),

    "created_at": FieldMetadata(
        name="created_at",
        classification="BACKEND_AUTO",
        description="Creation timestamp",
    ),

    "created_by": FieldMetadata(
        name="created_by",
        classification="CONTEXT",
        description="User UUID from auth context",
    ),

    # REQUIRED fields - must be populated (from NLP or user)
    "equipment_id": FieldMetadata(
        name="equipment_id",
        classification="REQUIRED",
        auto_populate_from="equipment",
        lookup_required=True,
        description="Equipment UUID (resolved from equipment name)",
    ),

    "title": FieldMetadata(
        name="title",
        classification="BACKEND_AUTO",
        auto_populate_from="equipment",
        compose_template="{equipment} - {symptom}",
        description="Work order title (composed from equipment and symptom)",
    ),

    # OPTIONAL fields - use defaults if not provided
    "priority": FieldMetadata(
        name="priority",
        classification="OPTIONAL",
        auto_populate_from="query_text",
        value_map={
            "urgent": "critical",
            "asap": "critical",
            "high": "high",
            "medium": "medium",
            "low": "low",
        },
        default="medium",
        options=["low", "medium", "high", "critical"],
        description="Work order priority (extracted from query or default to medium)",
    ),

    "wo_type": FieldMetadata(
        name="wo_type",
        classification="OPTIONAL",
        value_map={
            "emergency": "emergency",
            "urgent": "corrective",
            "preventive": "preventive",
            "predictive": "predictive",
            "project": "project",
        },
        default="corrective",
        options=["corrective", "preventive", "predictive", "emergency", "project"],
        description="Work order type",
    ),

    "description": FieldMetadata(
        name="description",
        classification="OPTIONAL",
        auto_populate_from="query_text",
        description="Work order description (from query text)",
    ),
}


# =============================================================================
# EXAMPLE 2: CREATE FAULT REPORT
# =============================================================================
# Query: "log fault P1234 on starboard generator low oil pressure"
# Entities: {fault_code: "P1234", equipment: "starboard generator", symptom: "low oil pressure"}

FAULT_REPORT_FIELD_METADATA = {
    "yacht_id": FieldMetadata(
        name="yacht_id",
        classification="CONTEXT",
    ),

    "id": FieldMetadata(
        name="id",
        classification="BACKEND_AUTO",
    ),

    "equipment_id": FieldMetadata(
        name="equipment_id",
        classification="REQUIRED",
        auto_populate_from="equipment",
        lookup_required=True,
        description="Equipment UUID",
    ),

    "fault_code": FieldMetadata(
        name="fault_code",
        classification="OPTIONAL",
        auto_populate_from="fault",
        description="Fault code (e.g., P1234)",
    ),

    "symptom": FieldMetadata(
        name="symptom",
        classification="REQUIRED",
        auto_populate_from="symptom",
        description="Fault symptom description",
    ),

    "severity": FieldMetadata(
        name="severity",
        classification="OPTIONAL",
        auto_populate_from="query_text",
        value_map={
            "critical": "critical",
            "urgent": "high",
            "high": "high",
            "medium": "medium",
            "low": "low",
        },
        default="medium",
        options=["low", "medium", "high", "critical"],
        description="Fault severity",
    ),

    "reported_at": FieldMetadata(
        name="reported_at",
        classification="BACKEND_AUTO",
    ),

    "reported_by": FieldMetadata(
        name="reported_by",
        classification="CONTEXT",
    ),
}


# =============================================================================
# EXAMPLE 3: REORDER PART
# =============================================================================
# Query: "reorder oil filter 10 units"
# Entities: {part: "oil filter", quantity: "10"}

REORDER_PART_FIELD_METADATA = {
    "yacht_id": FieldMetadata(
        name="yacht_id",
        classification="CONTEXT",
    ),

    "id": FieldMetadata(
        name="id",
        classification="BACKEND_AUTO",
    ),

    "part_id": FieldMetadata(
        name="part_id",
        classification="REQUIRED",
        auto_populate_from="part",
        lookup_required=True,
        description="Part UUID (resolved from part name)",
    ),

    "quantity": FieldMetadata(
        name="quantity",
        classification="REQUIRED",
        auto_populate_from="stock_calculation",
        description="Reorder quantity",
        # Note: stock_calculation is a special entity type that computes
        # reorder quantity based on min_stock, current_stock, etc.
    ),

    "priority": FieldMetadata(
        name="priority",
        classification="OPTIONAL",
        value_map={
            "urgent": "critical",
            "asap": "critical",
        },
        default="medium",
        options=["low", "medium", "high", "critical"],
    ),

    "notes": FieldMetadata(
        name="notes",
        classification="OPTIONAL",
        auto_populate_from="query_text",
        description="Additional notes",
    ),

    "requested_by": FieldMetadata(
        name="requested_by",
        classification="CONTEXT",
    ),

    "requested_at": FieldMetadata(
        name="requested_at",
        classification="BACKEND_AUTO",
    ),
}


# =============================================================================
# EXAMPLE 4: UPDATE EQUIPMENT STATUS
# =============================================================================
# Query: "mark port engine as failed"
# Entities: {equipment: "port engine", status: "failed"}

UPDATE_EQUIPMENT_STATUS_FIELD_METADATA = {
    "yacht_id": FieldMetadata(
        name="yacht_id",
        classification="CONTEXT",
    ),

    "equipment_id": FieldMetadata(
        name="equipment_id",
        classification="REQUIRED",
        auto_populate_from="equipment",
        lookup_required=True,
        description="Equipment UUID",
    ),

    "status": FieldMetadata(
        name="status",
        classification="REQUIRED",
        auto_populate_from="query_text",
        value_map={
            "operational": "operational",
            "working": "operational",
            "ok": "operational",
            "degraded": "degraded",
            "failing": "degraded",
            "failed": "failed",
            "broken": "failed",
            "maintenance": "maintenance",
            "servicing": "maintenance",
            "decommissioned": "decommissioned",
            "retired": "decommissioned",
        },
        options=["operational", "degraded", "failed", "maintenance", "decommissioned"],
        description="Equipment status",
    ),

    "notes": FieldMetadata(
        name="notes",
        classification="OPTIONAL",
        auto_populate_from="query_text",
        description="Status change notes",
    ),

    "updated_by": FieldMetadata(
        name="updated_by",
        classification="CONTEXT",
    ),

    "updated_at": FieldMetadata(
        name="updated_at",
        classification="BACKEND_AUTO",
    ),
}


# =============================================================================
# EXAMPLE 5: ASSIGN WORK ORDER
# =============================================================================
# Query: "assign WO-123 to john"
# Entities: {work_order: "WO-123", user: "john"}

ASSIGN_WORK_ORDER_FIELD_METADATA = {
    "yacht_id": FieldMetadata(
        name="yacht_id",
        classification="CONTEXT",
    ),

    "work_order_id": FieldMetadata(
        name="work_order_id",
        classification="REQUIRED",
        auto_populate_from="work_order",
        lookup_required=True,
        description="Work order UUID (resolved from WO number)",
    ),

    "assigned_to": FieldMetadata(
        name="assigned_to",
        classification="REQUIRED",
        auto_populate_from="query_text",
        # Note: User lookup would require a separate lookup_user_by_name function
        description="User UUID or name (requires user lookup)",
    ),

    "assigned_by": FieldMetadata(
        name="assigned_by",
        classification="CONTEXT",
    ),

    "assigned_at": FieldMetadata(
        name="assigned_at",
        classification="BACKEND_AUTO",
    ),

    "notes": FieldMetadata(
        name="notes",
        classification="OPTIONAL",
        auto_populate_from="query_text",
        description="Assignment notes",
    ),
}


# =============================================================================
# EXAMPLE USAGE
# =============================================================================

if __name__ == "__main__":
    """
    Example of how to use the prefill engine with the field metadata above.

    This would be called from a /prepare endpoint:

    @app.post("/v1/work-orders/prepare")
    async def prepare_work_order(request: PrepareRequest):
        # 1. Extract entities from NLP
        extracted_entities = await extract_entities(request.query_text)

        # 2. Build mutation preview
        preview = await build_mutation_preview(
            query_text=request.query_text,
            extracted_entities=extracted_entities,
            field_metadata=WORK_ORDER_FIELD_METADATA,
            yacht_id=request.yacht_id,
            supabase_client=get_supabase_client(),
            user_id=request.user_id,
        )

        # 3. Return preview to frontend
        return {
            "preview": preview["mutation_preview"],
            "missing_required": preview["missing_required"],
            "warnings": preview["warnings"],
            "dropdown_options": preview["dropdown_options"],
            "ready_to_commit": preview["ready_to_commit"],
        }
    """
    import asyncio
    from common.prefill_engine import build_mutation_preview

    async def example():
        # Simulated NLP extraction
        extracted_entities = {
            "equipment": "main engine",
            "symptom": "overheating",
            "priority": "urgent",
        }

        # Note: This requires a real Supabase client and yacht_id
        # Uncomment and configure for real usage:
        # from integrations.supabase import get_supabase_client
        # preview = await build_mutation_preview(
        #     query_text="create urgent work order for main engine overheating",
        #     extracted_entities=extracted_entities,
        #     field_metadata=WORK_ORDER_FIELD_METADATA,
        #     yacht_id="abc-123",
        #     supabase_client=get_supabase_client(),
        #     user_id="user-456",
        # )
        # print(preview)

        print("Example field metadata loaded successfully!")
        print(f"Work Order fields: {list(WORK_ORDER_FIELD_METADATA.keys())}")

    asyncio.run(example())
