/**
 * Work Orders — static mock data for Phase 1E list view.
 * Replace with live data from ENGINEER01's
 * GET /api/vessel/{id}/domain/work_orders/records endpoint.
 */

import type { ListRecord } from '../DomainListView';

export const MOCK_WORK_ORDER_RECORDS: ListRecord[] = [
  {
    id: 'WO-1042',
    ref: 'WO\u00b71042',
    title: 'Main Engine Inspection',
    meta: 'E-007 Main Engine \u00b7 Planned \u00b7 Due 22 Mar',
    assignedTo: 'J. Morrison',
    status: 'Overdue',
    statusVariant: 'overdue',
    severity: 'critical',
    age: '5d',
    searchText: 'wo-1042 wo·1042 main engine inspection e-007 planned overdue j. morrison',
  },
  {
    id: 'WO-1038',
    ref: 'WO\u00b71038',
    title: 'Generator Service \u2014 500hr',
    meta: 'E-012 Stbd Generator \u00b7 Running Hours \u00b7 Due 28 Mar',
    assignedTo: 'R. Costa',
    status: 'Due Soon',
    statusVariant: 'warn',
    severity: 'warning',
    age: '2d',
    searchText: 'wo-1038 wo·1038 generator service 500hr e-012 stbd generator running hours due soon r. costa',
  },
  {
    id: 'WO-1035',
    ref: 'WO\u00b71035',
    title: 'Watermaker Membrane Replace',
    meta: 'E-022 Watermaker \u00b7 Reactive \u00b7 No due date',
    assignedTo: undefined,
    status: 'Open',
    statusVariant: 'open',
    age: '8d',
    searchText: 'wo-1035 wo·1035 watermaker membrane replace e-022 reactive open unassigned',
  },
  {
    id: 'WO-1031',
    ref: 'WO\u00b71031',
    title: 'Bow Thruster Annual Service',
    meta: 'E-019 Bow Thruster \u00b7 Planned \u00b7 Due 15 Apr',
    assignedTo: 'J. Morrison',
    status: 'Open',
    statusVariant: 'open',
    age: '1d',
    searchText: 'wo-1031 wo·1031 bow thruster annual service e-019 planned open j. morrison',
  },
  {
    id: 'WO-1028',
    ref: 'WO\u00b71028',
    title: 'AC System Filter Replacement',
    meta: 'E-041 AC Unit 3 \u00b7 Planned \u00b7 Due 10 Apr',
    assignedTo: 'R. Costa',
    status: 'In Progress',
    statusVariant: 'pending',
    age: '3d',
    searchText: 'wo-1028 wo·1028 ac system filter replacement e-041 ac unit 3 planned in progress r. costa',
  },
  {
    id: 'WO-1024',
    ref: 'WO\u00b71024',
    title: 'Liferaft Annual Inspection',
    meta: 'E-050 Liferaft Port \u00b7 Compliance \u00b7 Due 5 Apr',
    assignedTo: 'J. Morrison',
    status: 'Open',
    statusVariant: 'open',
    age: '6d',
    searchText: 'wo-1024 wo·1024 liferaft annual inspection e-050 liferaft port compliance open j. morrison',
  },
  {
    id: 'WO-1020',
    ref: 'WO\u00b71020',
    title: 'Hull Zinc Anode Replacement',
    meta: 'E-001 Hull \u00b7 Planned \u00b7 Next haul-out',
    assignedTo: undefined,
    status: 'Open',
    statusVariant: 'open',
    age: '14d',
    searchText: 'wo-1020 wo·1020 hull zinc anode replacement e-001 hull planned open unassigned',
  },
  {
    id: 'WO-1018',
    ref: 'WO\u00b71018',
    title: 'Navigation Light Port Side Replace',
    meta: 'E-033 Nav Lights \u00b7 Reactive \u00b7 Completed',
    assignedTo: 'R. Costa',
    status: 'Closed',
    statusVariant: 'signed',
    age: '18d',
    searchText: 'wo-1018 wo·1018 navigation light port side replace e-033 nav lights reactive closed r. costa',
  },
];
