-- Migration: Optional indexes for doc_metadata table
-- Feature: P1 Show Related - JSONB and array query optimization
-- Date: 2026-01-28
-- Status: COMMENTED OUT BY DEFAULT
-- Idempotent: Safe to rerun if uncommented

-- =============================================================================
-- ⚠️  IMPORTANT: READ BEFORE UNCOMMENTING ⚠️
-- =============================================================================
-- This migration is COMMENTED OUT by default.
-- Only uncomment if EXPLAIN ANALYZE shows sequential scans with cost > 1000.
--
-- These indexes optimize queries on doc_metadata table:
-- 1. equipment_ids[] array containment (@> operator)
-- 2. metadata JSONB queries (jsonb_path_ops)
-- 3. entity_type/entity_id extraction from JSONB
--
-- BEFORE uncommenting, run performance tests (see section below).
-- Premature indexing wastes space and slows writes.
-- =============================================================================

-- =============================================================================
-- PERFORMANCE TESTING (RUN THESE FIRST)
-- =============================================================================
-- Test 1: Equipment array containment query
-- EXPLAIN ANALYZE
-- SELECT id, filename FROM doc_metadata
-- WHERE equipment_ids @> ARRAY['<test-equipment-id>']::uuid[]
--   AND yacht_id = '<test-yacht-id>'
--   AND deleted_at IS NULL
-- LIMIT 20;
--
-- Test 2: Metadata JSONB query
-- EXPLAIN ANALYZE
-- SELECT id, filename FROM doc_metadata
-- WHERE metadata @> jsonb_build_object('entity_type', 'work_order', 'entity_id', '<test-wo-id>')
--   AND yacht_id = '<test-yacht-id>'
--   AND deleted_at IS NULL
-- LIMIT 20;
--
-- DECISION TREE:
-- - If cost < 100 → No index needed (table is small or query is efficient)
-- - If "Bitmap Heap Scan" with "GIN" → Index is already working (good!)
-- - If "Seq Scan" with cost > 1000 → Uncomment relevant index below
-- =============================================================================

-- =============================================================================
-- INDEX 1: GIN index on equipment_ids[] array
-- =============================================================================
-- Uncomment if "WHERE equipment_ids @> ARRAY[...]" shows Seq Scan with cost > 1000

-- CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_doc_metadata_equipment_ids_gin
-- ON doc_metadata USING GIN (equipment_ids);
--
-- COMMENT ON INDEX idx_doc_metadata_equipment_ids_gin IS
-- 'Optimizes queries: WHERE equipment_ids @> ARRAY[...]. Added in P1 Show Related (2026-01-28)';

-- =============================================================================
-- INDEX 2: GIN index on metadata JSONB (jsonb_path_ops)
-- =============================================================================
-- Uncomment if "WHERE metadata @> jsonb_build_object(...)" shows Seq Scan with cost > 1000

-- CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_doc_metadata_metadata_gin
-- ON doc_metadata USING GIN (metadata jsonb_path_ops);
--
-- COMMENT ON INDEX idx_doc_metadata_metadata_gin IS
-- 'Optimizes queries: WHERE metadata @> jsonb_build_object(...). Uses jsonb_path_ops for smaller index size. Added in P1 Show Related (2026-01-28)';

-- =============================================================================
-- INDEX 3: Composite btree index on extracted entity_type + entity_id
-- =============================================================================
-- Uncomment if JSONB extraction is frequent and GIN index doesn't help enough
-- This index is larger but provides faster lookups for specific entity_type/entity_id pairs

-- CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_doc_metadata_entity_type_id
-- ON doc_metadata (
--     (metadata->>'entity_type'),
--     (metadata->>'entity_id'),
--     yacht_id
-- )
-- WHERE deleted_at IS NULL;
--
-- COMMENT ON INDEX idx_doc_metadata_entity_type_id IS
-- 'Optimizes queries extracting entity_type and entity_id from JSONB metadata. Btree index for equality lookups. Added in P1 Show Related (2026-01-28)';

-- =============================================================================
-- VERIFICATION (if indexes are uncommented)
-- =============================================================================
-- SELECT schemaname, tablename, indexname, indexdef
-- FROM pg_indexes
-- WHERE tablename = 'doc_metadata'
--   AND indexname LIKE 'idx_doc_metadata_%'
-- ORDER BY indexname;
--
-- Expected: Shows created indexes (if uncommented)

-- =============================================================================
-- ROLLBACK (if indexes cause issues)
-- =============================================================================
-- DROP INDEX CONCURRENTLY IF EXISTS idx_doc_metadata_equipment_ids_gin;
-- DROP INDEX CONCURRENTLY IF EXISTS idx_doc_metadata_metadata_gin;
-- DROP INDEX CONCURRENTLY IF EXISTS idx_doc_metadata_entity_type_id;

-- =============================================================================
-- WHEN TO UNCOMMENT
-- =============================================================================
-- Index 1 (equipment_ids GIN):
--   - When Query 2A (manuals) or Query 5B (attachments) shows Seq Scan > 1000 cost
--   - When doc_metadata has > 10,000 rows with equipment_ids[] populated
--
-- Index 2 (metadata JSONB GIN):
--   - When Query 5A (attachments by entity_id) shows Seq Scan > 1000 cost
--   - When doc_metadata has > 10,000 rows with metadata JSONB populated
--
-- Index 3 (entity_type + entity_id btree):
--   - When extracting entity_type/entity_id is frequent and GIN index doesn't help
--   - When specific entity lookups are slow despite GIN index
-- =============================================================================

-- Migration complete (no changes applied; indexes commented out)
-- Revisit after production profiling shows actual query patterns
