-- COMPLETED 2026-03-18: Fixed 248 stranded records with NULL/empty search_text
--
-- Affected: certificate(38), receiving(175), email(11), handover_item(24)
--
-- Root cause: projection worker's source_version guard
-- (WHERE search_index.source_version < EXCLUDED.source_version)
-- blocked upserts because claim_batch returns the same source_version
-- already in the row. The worker marked items 'indexed' without
-- actually writing search_text.
--
-- Fix applied manually:
-- 1. Called entity_serializer_sync directly to compute search_text
-- 2. Wrote search_text + updated content_hash via direct UPDATE
-- 3. Re-queued 248 embedding_jobs to regenerate embeddings
-- 4. Embedding worker processed all 248 (3 batches, 0 failures)
--
-- This migration is a no-op (already applied). Kept for audit trail.
-- If re-running on a fresh DB, the projection worker handles these
-- correctly on first insert — this bug only affects rows that were
-- inserted with empty search_text before entity_serializer_sync existed.

-- No-op: SELECT 1;
