"""
Schema Constants - Single Source of Truth
==================================================
Generated from actual production database on 2026-01-23.
DO NOT manually edit - regenerate from DB when schema changes.

Usage:
    from schema_constants import PmsFaultsSchema as Faults
    db.table(Faults.TABLE).select(Faults.FAULT_CODE).execute()
"""


class PmsFaultsSchema:
    """Schema for pms_faults table"""
    TABLE = "pms_faults"

    CREATED_AT = "created_at"
    DELETED_AT = "deleted_at"
    DELETED_BY = "deleted_by"
    DELETION_REASON = "deletion_reason"
    DESCRIPTION = "description"
    DETECTED_AT = "detected_at"
    EQUIPMENT_ID = "equipment_id"
    FAULT_CODE = "fault_code"
    ID = "id"
    METADATA = "metadata"
    RESOLVED_AT = "resolved_at"
    RESOLVED_BY = "resolved_by"
    SEVERITY = "severity"
    STATUS = "status"
    TITLE = "title"
    UPDATED_AT = "updated_at"
    UPDATED_BY = "updated_by"
    WORK_ORDER_ID = "work_order_id"
    YACHT_ID = "yacht_id"

class PmsWorkOrdersSchema:
    """Schema for pms_work_orders table"""
    TABLE = "pms_work_orders"

    ASSIGNED_TO = "assigned_to"
    COMPLETED_AT = "completed_at"
    COMPLETED_BY = "completed_by"
    COMPLETION_NOTES = "completion_notes"
    CREATED_AT = "created_at"
    CREATED_BY = "created_by"
    DELETED_AT = "deleted_at"
    DELETED_BY = "deleted_by"
    DELETION_REASON = "deletion_reason"
    DESCRIPTION = "description"
    DUE_DATE = "due_date"
    DUE_HOURS = "due_hours"
    EQUIPMENT_ID = "equipment_id"
    FAULT_ID = "fault_id"
    FREQUENCY = "frequency"
    ID = "id"
    LAST_COMPLETED_DATE = "last_completed_date"
    LAST_COMPLETED_HOURS = "last_completed_hours"
    METADATA = "metadata"
    PRIORITY = "priority"
    STATUS = "status"
    TITLE = "title"
    TYPE = "type"
    UPDATED_AT = "updated_at"
    UPDATED_BY = "updated_by"
    VENDOR_CONTACT_HASH = "vendor_contact_hash"
    WO_NUMBER = "wo_number"
    WORK_ORDER_TYPE = "work_order_type"
    YACHT_ID = "yacht_id"

class PmsWorkOrderNotesSchema:
    """Schema for pms_work_order_notes table"""
    TABLE = "pms_work_order_notes"

    CREATED_AT = "created_at"
    CREATED_BY = "created_by"
    ID = "id"
    METADATA = "metadata"
    NOTE_TEXT = "note_text"
    NOTE_TYPE = "note_type"
    WORK_ORDER_ID = "work_order_id"

class PmsWorkOrderPartsSchema:
    """Schema for pms_work_order_parts table"""
    TABLE = "pms_work_order_parts"

    CREATED_AT = "created_at"
    DELETED_AT = "deleted_at"
    DELETED_BY = "deleted_by"
    ID = "id"
    NOTES = "notes"
    PART_ID = "part_id"
    QUANTITY = "quantity"
    UPDATED_AT = "updated_at"
    WORK_ORDER_ID = "work_order_id"

class PmsPartsSchema:
    """Schema for pms_parts table"""
    TABLE = "pms_parts"

    CATEGORY = "category"
    CREATED_AT = "created_at"
    DESCRIPTION = "description"
    EMBEDDING_TEXT = "embedding_text"
    ID = "id"
    LAST_COUNTED_AT = "last_counted_at"
    LAST_COUNTED_BY = "last_counted_by"
    LOCATION = "location"
    MANUFACTURER = "manufacturer"
    METADATA = "metadata"
    MINIMUM_QUANTITY = "minimum_quantity"
    MODEL_COMPATIBILITY = "model_compatibility"
    NAME = "name"
    PART_NUMBER = "part_number"
    QUANTITY_ON_HAND = "quantity_on_hand"
    SEARCH_EMBEDDING = "search_embedding"
    UNIT = "unit"
    UPDATED_AT = "updated_at"
    YACHT_ID = "yacht_id"

class PmsPartUsageSchema:
    """Schema for pms_part_usage table"""
    TABLE = "pms_part_usage"

    EQUIPMENT_ID = "equipment_id"
    ID = "id"
    METADATA = "metadata"
    NOTES = "notes"
    PART_ID = "part_id"
    QUANTITY = "quantity"
    USAGE_REASON = "usage_reason"
    USED_AT = "used_at"
    USED_BY = "used_by"
    WORK_ORDER_ID = "work_order_id"
    YACHT_ID = "yacht_id"

class PmsPurchaseOrdersSchema:
    """Schema for pms_purchase_orders table"""
    TABLE = "pms_purchase_orders"

    APPROVAL_NOTES = "approval_notes"
    APPROVED_AT = "approved_at"
    APPROVED_BY = "approved_by"
    CREATED_AT = "created_at"
    CURRENCY = "currency"
    ID = "id"
    METADATA = "metadata"
    ORDERED_AT = "ordered_at"
    ORDERED_BY = "ordered_by"
    PO_NUMBER = "po_number"
    RECEIVED_AT = "received_at"
    RECEIVED_BY = "received_by"
    RECEIVING_NOTES = "receiving_notes"
    STATUS = "status"
    SUPPLIER_ID = "supplier_id"
    UPDATED_AT = "updated_at"
    YACHT_ID = "yacht_id"

class PmsAuditLogSchema:
    """Schema for pms_audit_log table"""
    TABLE = "pms_audit_log"

    ACTION = "action"
    CREATED_AT = "created_at"
    ENTITY_ID = "entity_id"
    ENTITY_TYPE = "entity_type"
    ID = "id"
    METADATA = "metadata"
    NEW_VALUES = "new_values"
    OLD_VALUES = "old_values"
    SIGNATURE = "signature"
    USER_ID = "user_id"
    YACHT_ID = "yacht_id"


class PmsVesselCertificatesSchema:
    """Schema for pms_vessel_certificates table"""
    TABLE = "pms_vessel_certificates"

    CERTIFICATE_NAME = "certificate_name"
    CERTIFICATE_NUMBER = "certificate_number"
    CERTIFICATE_TYPE = "certificate_type"
    CREATED_AT = "created_at"
    DOCUMENT_ID = "document_id"
    EXPIRY_DATE = "expiry_date"
    ID = "id"
    ISSUE_DATE = "issue_date"
    ISSUING_AUTHORITY = "issuing_authority"
    LAST_SURVEY_DATE = "last_survey_date"
    NEXT_SURVEY_DUE = "next_survey_due"
    PROPERTIES = "properties"
    STATUS = "status"
    YACHT_ID = "yacht_id"


class PmsCrewCertificatesSchema:
    """Schema for pms_crew_certificates table"""
    TABLE = "pms_crew_certificates"

    CERTIFICATE_NUMBER = "certificate_number"
    CERTIFICATE_TYPE = "certificate_type"
    CREATED_AT = "created_at"
    DOCUMENT_ID = "document_id"
    EXPIRY_DATE = "expiry_date"
    ID = "id"
    ISSUE_DATE = "issue_date"
    ISSUING_AUTHORITY = "issuing_authority"
    PERSON_NAME = "person_name"
    PERSON_NODE_ID = "person_node_id"
    PROPERTIES = "properties"
    YACHT_ID = "yacht_id"
